#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THIRD_PARTY_DIR="$PROJECT_ROOT/third_party"
UPSTREAM_LOCK_DOC="$PROJECT_ROOT/docs/upstream-commits.md"

clone_or_update() {
  local name="$1"
  local url="$2"
  local dest="$THIRD_PARTY_DIR/$name"

  if [[ -d "$dest/.git" ]]; then
    printf '\n===== update %s =====\n' "$name"
    printf '$ git -C %q fetch --all --tags --prune\n' "$dest"
    git -C "$dest" fetch --all --tags --prune
    printf '$ git -C %q pull --ff-only\n' "$dest"
    git -C "$dest" pull --ff-only
  elif [[ -e "$dest" ]]; then
    printf '[error] %s exists but is not a git repository\n' "$dest" >&2
    return 1
  else
    printf '\n===== clone %s =====\n' "$name"
    printf '$ git clone %q %q\n' "$url" "$dest"
    git clone "$url" "$dest"
  fi
}

mkdir -p "$THIRD_PARTY_DIR"

clone_or_update python-validity https://github.com/uunicorn/python-validity
clone_or_update open-fprintd https://github.com/uunicorn/open-fprintd

PYTHON_VALIDITY_HASH="$(git -C "$THIRD_PARTY_DIR/python-validity" rev-parse HEAD)"
OPEN_FPRINTD_HASH="$(git -C "$THIRD_PARTY_DIR/open-fprintd" rev-parse HEAD)"

printf '\n===== upstream commit hashes =====\n'
printf 'python-validity: %s\n' "$PYTHON_VALIDITY_HASH"
printf 'open-fprintd: %s\n' "$OPEN_FPRINTD_HASH"

{
  printf '# Upstream commits\n\n'
  printf 'Generated by `scripts/fetch-upstream.sh`.\n\n'
  printf '%s\n' "- \`python-validity\`: \`$PYTHON_VALIDITY_HASH\`"
  printf '%s\n' "- \`open-fprintd\`: \`$OPEN_FPRINTD_HASH\`"
} > "$UPSTREAM_LOCK_DOC"
